### ISSUE TITLE
Issues when testing the tool locally

### ISSUE THREAD

**Issue by pvanliefland** [BLSQ/geohealthaccess#2]
I'm currently trying to follow the example with Burundi.

I'm building the Docker image myself using `docker build -t geohealthaccess .`.

Then, downloading the data using `docker run -v $(pwd):/project:rw geohealthaccess download -c BDI -u redacted -p redacted`. One small issue there: I'm forced to provide the earthdata username and password even if my environment variables are defined.

Moving on to `preprocess` using `docker run -v $(pwd):/project:rw geohealthaccess preprocess -c BDI --crs "EPSG:3857" --resolution 100`.

Finally running `geohealthaccess access --car --walk`, which completes, but the result is that only two out of 6 tif files appear to be properly generated (only `backlink_car_health.tif` and `backlink_walk_health.tif` seem to work).

In my console, I see the following warnings and errors:

```

2020-10-05 15:34:10 INFO [grasshelper]: GRASS environment initialized.
WARNING: Updating spatial reference with embedded proj4 definition
WARNING: Updating spatial reference with embedded proj4 definition
ERROR 6: SetColorTable() only supported for Byte or UInt16 bands in TIFF format.
ERROR 6: SetColorTable() only supported for Byte or UInt16 bands in TIFF format.
```

## Issues recap

- [x] Setting the `EARTHDATA_USERNAME` and `EARTHDATA_PASSWORD` is not enough to download the data - looks like the `--earthdata-user` and `--earthdata-pass` options are mandatory
- [x] Issue with generated TIF files

**Comment by yannforget** [comment]
Hi Pierre and thanks for the detailed report!

Regarding the environment variables, that is because the program runs inside a Docker container. You can pass them to the container using `run -e EARTHDATA_USERNAME='something' -e EARTHDATA_PASSWORD='password'` or with an env file: `run --env-file /path/to/envfile` when running the geohealthaccess container.

I'm gonna look at the GRASS warnings but I think they don't matter in our case -- we don't use the ColorTable feature of the GeoTIFF format.

What is the problem with the GeoTIFFs that are not properly generated?

Thanks again!

Yann

**Comment by pvanliefland** [comment]
Closing, as the TIF files appear to be correct - just not regular TIF files that generic apps like Apple Preview can open.
